---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - immudb.io
  resources:
  - immudbs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - immudb.io
  resources:
  - immudbs/finalizers
  verbs:
  - update
- apiGroups:
  - immudb.io
  resources:
  - immudbs/status
  verbs:
  - get
  - patch
  - update
